import assert from "node:assert/strict";
import {chromium} from "playwright";

const browser=await chromium.launch({headless:true});
const ctx=await browser.newContext({viewport:{width:390,height:760},deviceScaleFactor:1,isMobile:true,hasTouch:true});
const page=await ctx.newPage();
const errors=[];
page.on("pageerror",e=>errors.push(String(e)));
const url="http://127.0.0.1:8000/";
try{
  await page.goto(url);
  await page.waitForFunction(()=>document.querySelector("#progress-label").textContent.includes("/ 80"));
  await page.locator("#start").click();
  await page.locator("#card:not(.hidden)").waitFor({timeout:6000}).catch(async e=>{console.log("INITIAL CARD",await page.evaluate(()=>({card:document.querySelector("#card").outerHTML.slice(0,300),empty:document.querySelector("#empty").textContent,start:document.querySelector("#start").outerHTML,progress:document.querySelector("#progress-label").textContent,storage:JSON.parse(localStorage.getItem("eng-forever-v1"))})),errors);throw e;});
  const first=await page.locator("#card-id").textContent();
  assert.match(first,/№ \d+/);
  assert.equal(await page.locator("#wrong").isDisabled(),true,"Answer must be opened before responding");
  const hiddenAnswer=await page.locator(".answer-content").evaluate(el=>getComputedStyle(el).display);
  assert.equal(hiddenAnswer,"none","English answer leaks out of closed curtain");
  const sheetY=await page.locator("#sheet-handle").boundingBox();
  const promptY=await page.locator("#question-text").boundingBox();
  assert.ok(sheetY.y<promptY.y,"Curtain must be at the TOP of the card, above the prompt");
  await page.locator("#sheet-handle").click();
  assert.equal(await page.locator("#wrong").isEnabled(),true,"Tap fallback must open the answer");
  assert.notEqual(await page.locator(".answer-content").evaluate(el=>getComputedStyle(el).display),"none");
  await page.locator("#right").click();
  await page.waitForFunction(old=>document.querySelector("#card-id").textContent!==old,first,{timeout:6000}).catch(async error=>{console.log("AFTER RIGHT",await page.evaluate(()=>({progress:document.querySelector("#progress-label").textContent,card:document.querySelector("#card").className,stored:JSON.parse(localStorage.getItem("eng-forever-v1"))?.current,queue:JSON.parse(localStorage.getItem("eng-forever-v1"))?.queue?.length})),errors);throw error;});
  assert.notEqual(await page.locator("#card-id").textContent(),first,"Next phrase must appear after marking correct");
  assert.match(await page.locator("#progress-label").textContent(),/^1 \/ 80 пройдено$/);
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem("eng-forever-v1")));
  assert.ok(saved.cards[first.replace("№ ","")].learned,"Progress must persist to storage");
  // Verify downward dragging the handle, rather than accidental card swipe.
  const h=await page.locator("#sheet-handle").boundingBox();
  await page.mouse.move(h.x+h.width/2,h.y+h.height/2);
  await page.mouse.down();
  await page.mouse.move(h.x+h.width/2,h.y+h.height/2+65,{steps:7});
  await page.mouse.up();
  assert.equal(await page.locator("#right").isEnabled(),true,"Downward drag must open the curtain");
  const second=await page.locator("#card-id").textContent();
  // Swipe left on the exposed card: records an error and moves to a new phrase.
  const card=await page.locator("#card").boundingBox();
  await page.mouse.move(card.x+card.width*.7,card.y+card.height*.72);
  await page.mouse.down();
  await page.mouse.move(card.x+card.width*.2,card.y+card.height*.72,{steps:9});
  await page.mouse.up();
  await page.waitForFunction(old=>document.querySelector("#card-id").textContent!==old,second,{timeout:6000});
  const afterWrong=await page.evaluate(()=>JSON.parse(localStorage.getItem("eng-forever-v1")));
  assert.equal(afterWrong.cards[second.replace("№ ","")].attempts,1,"Swipe left must count as one attempt");
  assert.equal(afterWrong.cards[second.replace("№ ","")].correct,0,"Swipe left must count as error");
  assert.ok(afterWrong.roundSeen.includes(Number(second.replace("№ ",""))),"Wrong phrase counts as seen once");
  assert.ok(!afterWrong.queue.includes(Number(second.replace("№ ",""))),"Wrong phrase must wait for the next round");
  assert.match(await page.locator("#progress-label").textContent(),/^2 \/ 80 пройдено$/);
  await page.reload();
  await page.locator("#card:not(.hidden)").waitFor();
  assert.equal(await page.locator("#right").isDisabled(),true,"Revealed answer must not survive reload");
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);
  assert.ok(overflow<=1,"Mobile layout must not overflow horizontally: "+overflow);
  await page.locator("#settings-open").click();
  assert.equal(await page.locator("#settings-dialog").evaluate(el=>el.open),true,"Settings must open");
  assert.equal(await page.locator("#phrase-list .phrase-option").count(),80,"All 80 numbered phrases must appear in settings");
  assert.deepEqual(await page.locator("#phrase-list .phrase-option").evaluateAll(items=>items.map(x=>parseInt(x.textContent.slice(1),10))),Array.from({length:80},(_,i)=>i+1),"Settings IDs must match original notebook numbers 1–80");
  assert.equal(await page.locator("#phrase-list").evaluate(el=>getComputedStyle(el).overflowY),"visible","Phrase list should not have a hidden nested scrollbar");
  await page.locator("#phrase-list .phrase-option").last().scrollIntoViewIfNeeded();
  assert.equal(await page.locator("#phrase-list .phrase-option").last().isVisible(),true,"ID 80 must be reachable at bottom of settings");
  // Existing history must survive manually re-enabling a learned phrase.
  const oldId=Number(first.replace("№ ",""));
  const before=await page.evaluate(id=>{
    const c=JSON.parse(localStorage.getItem("eng-forever-v1")).cards[id];
    return {attempts:c.attempts,correct:c.correct,hardness:c.hardness,history:c.history};
  },oldId);
  const oldCheckbox=page.locator("#phrase-list .phrase-option").nth(oldId-1).locator("input");
  assert.equal(await oldCheckbox.isChecked(),false,"Learned card is inactive before manual selection");
  await oldCheckbox.check();
  let state=await page.evaluate(()=>JSON.parse(localStorage.getItem("eng-forever-v1")));
  assert.equal(state.started,false,"Manual checkbox must stop current training");
  assert.equal(state.round,1,"A manually changed selection must reset round number");
  assert.equal(state.current,null,"No card should remain after manual selection");
  assert.deepEqual(state.queue,[],"Previous randomized queue must be discarded");
  assert.deepEqual({attempts:state.cards[oldId].attempts,correct:state.cards[oldId].correct,hardness:state.cards[oldId].hardness,history:state.cards[oldId].history},before,"Manual selection must preserve history and difficulty");
  await page.locator("#settings-done").click();
  assert.equal(await page.locator("#settings-dialog").evaluate(el=>el.open),false,"Settings must close");
  assert.equal(await page.locator("#start").isVisible(),true,"Home must show Start training after checkbox change");
  await page.reload();
  assert.equal(await page.locator("#start").isVisible(),true,"New training state survives page reload");
  await page.locator("#start").click();
  await page.locator("#card:not(.hidden)").waitFor();
  await page.locator("#settings-open").click();
  assert.equal(await page.locator("#select-all").count(),1,"Keep Select all button");
  assert.equal(await page.locator("#select-none").count(),1,"Keep Deselect all button");
  await page.locator("#select-none").click();
  state=await page.evaluate(()=>JSON.parse(localStorage.getItem("eng-forever-v1")));
  assert.equal(state.started,false,"Deselect all starts a new training");
  assert.equal(state.round,1);
  assert.equal(state.current,null);
  assert.equal(await page.locator("#phrase-list input:checked").count(),0);
  await page.locator("#select-all").click();
  state=await page.evaluate(()=>JSON.parse(localStorage.getItem("eng-forever-v1")));
  assert.equal(state.started,false,"Select all returns to start screen, not an auto-started session");
  assert.equal(state.round,1);
  assert.equal(state.current,null);
  assert.equal(await page.locator("#phrase-list input:checked").count(),80);
  assert.deepEqual({attempts:state.cards[oldId].attempts,correct:state.cards[oldId].correct,hardness:state.cards[oldId].hardness,history:state.cards[oldId].history},before,"Bulk operations preserve history and difficulty");
  await page.locator("#settings-done").click();
  assert.equal(await page.locator("#start").isVisible(),true);
  await page.locator("#start").click();
  await page.locator("#card:not(.hidden)").waitFor();
  assert.equal(await page.locator("#round-label").textContent(),"Круг 1");
  await page.locator("#settings-open").click();
  const currentId=Number((await page.locator("#card-id").textContent()).replace("№ ",""));
  await page.locator("#phrase-list .phrase-option").nth(currentId-1).locator("input").uncheck();
  state=await page.evaluate(()=>JSON.parse(localStorage.getItem("eng-forever-v1")));
  assert.equal(state.started,false,"Deselecting a single phrase also resets the current session");
  await page.locator("#settings-done").click();
  assert.equal(await page.locator("#start").isVisible(),true);
  assert.deepEqual(errors,[],"No uncaught runtime exceptions");
  console.log("PASS: 390px mobile layout, hidden answer, top curtain, tap and down-drag reveal, swipe error, next card, persistence and settings");
}finally{await browser.close();}
